# ---------------------------------------------------------------------------
# ClipYemen.py
# Created on: 2012-03-20 10:03:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
# Local variables:
Cities = "Cities"
Yemen_ = "Yemen"
ClipYemen = "D:\\VYUKA\\II - SKRI\\Cviceni\\Database\\World.mdb\\Yemen\\ClipYemen"

# Process: Clip
arcpy.Clip_analysis(Cities, Yemen_, ClipYemen, "")

# ---DESCRIBE------------------------------------------------------------------------
import arcpy
from arcpy import env

# Create a Describe object from the feature class

#env.Workspace = "D:\\Vyuka\\II - SKRI\\Cviceni\\"
desc = arcpy.Describe("D:\\Vyuka\\II - SKRI\\Cviceni\\Database\\SanDiego.mdb\\Freeways")

# Print some feature class properties
#
print "Feature Type:  " + desc.featureType
print "Shape Type :   " + desc.shapeType
print "Spatial Index: " + str(desc.hasSpatialIndex)

# ---TRY-EXCEPT--------------------------------------------------------------------
import  arcpy as ap
try:
  # chybi workspace, kde je Railroads?, kam umistit vysledek Rail100 ?
  ap.Buffer_analysis("Railroads","Rail100",100)
except:
  # tisk ale jen do PythonWin
  print ap.GetMessages()
  # zkuste bez hlaseni i s hlasenim
  # bez hlaseni se jevi, jako ze vse probehlo spravne
  ap.AddMessage("Zde je hlaseni skriptu, pokud neco probehlo chybne. ")
  ap.AddMessage(" *********************************")
  ap.AddMessage(" ")
  ap.AddWarning(ap.GetMessages())
  ap.AddMessage(" ")

# ---CREATE-FOLDER-----------------------------------------------------------------
# Create the geoprocessor object
import arcpy
# nastaveni licence
arcpy.SetProduct("ArcView")
# Set the workspace environment setting.
arcpy.Workspace = "C:\\temp\\"
# Create a new folder in the workspace.
# If exist - no error message. gp.OverwriteOutput is not necessary.
arcpy.CreateFolder_management(arcpy.Workspace, "MyFolder")

# ---DESCRIBE----------------------------------------------------------------
# Cviceni 5 / Describe
import arcgisscripting
# Create the Geoprocessor object
gp = arcgisscripting.create(9.3)

if gp.exists("D:\\Vyuka\\II - SKRI/Cviceni/Database"):

    gp.Workspace = "D:\\Vyuka\\II - SKRI/Cviceni/Database"
    print "Prac. databaze nastavena"

print "Popis FEATURE CLASS    "
#dscFC=gp.Describe("Redlands.mdb\\Hospitals")
dscFC=gp.Describe("Redlands.mdb\\Parcels")
print dscFC.featureType
print dscFC.ShapeType
print dscFC.DataSetType
print dscFC.DataType

print dscFC.CatalogPath
# obdelnik
print dscFC.Extent

### zjisten identifikatoru zda existuje
print dscFC.HasOID
### nazev identifikatoru
print dscFC.OIDFieldName


print "Dataset INFO"
dscDS=gp.Describe("Redlands.mdb\\Census")
print dscDS.Extent
print dscDS.DataSetType

print "SHP INFO"
gp.Workspace = "D:\\Vyuka\\II - SKRI\\Cviceni\\Database\\World"
##dscSH=gp.Describe("Cities.shp")
##print dscSH.ShapeType
##print dscSH.FeatureType

print "SHP INFO"
dscSH=gp.Describe("Highways.shp")
print dscSH.ShapeType
print dscSH.FeatureType
print dscSH.HasSpatialIndex

### nazev atributu s geoemtrii
print dscSH.ShapeFieldName

print "GEODB INFO"
gp.Workspace = "D:\\Vyuka\\II - SKRI/Cviceni/Database"
dscWS=gp.Describe("World.mdb")
print dscWS.Domains

print "DataType univerzalni vlastnost"
print dscWS.DataType

##
print dscWS.WorkSpaceType
print dscWS.catalogPath

# ---CHECK FOLDER EXISTS----------------------------------------------------------------
# import geoprocessor object
import arcpy as ap

# Print whether or not the folder exists to the Interactive Window.
if ap.Exists("C:\\temp\\MyFolder"):
    print "exists"

# Overeni existence adresare se zapisem jednoduchych zpetnych lomitek, nutne uvest r
if ap.Exists(r"C:\temp\MyFolder"):
    print "exists i se zapisem r"


# ---EXISTS-DIRECTORY----------------------------------------------------------------
import arcpy
from arcpy import env

# Set the current workspace
env.workspace = "C:/Temp/"

# Check for existance of the directory Roads
if arcpy.Exists("Roads"):
    arcpy.Delete_management("Roads")
    print "smazano"
else:
    arcpy.CreateFolder_management(env.workspace, "Roads")
    print "vytvoreno"


# ---LIST-FIELDS----------------------------------------------------------------
# Purpose: Lists all the fields in a feature class and prints the name,
#          type, and length of each field to the Interactive Window.

import arcpy as ap
import string, os

ap.env.workspace = "D:\\vyuka\\II - SKRI\\Cviceni\\Database\\Redlands.mdb"

ap.OverwriteOutput=1

# List all the fields in the Streets feature class.
#fldList = ap.ListFields("Streets", "*", "All")
fldList = ap.ListFields("Streets")


# Loop through each field and print the name, type, and length to the
# Interactive Window.
for fld in fldList:
    print fld.name
    print fld.type
    print fld.name + " is a " + fld.type + " field with a length of " + str(fld.length)


# ---RASTR.LIST-PYRAMIDY----------------------------------------------------------------
# Author:
# Date:
# Purpose: zjisti pocet rastrovych sad zacinajicich v nazvu "a" a vytvori pro ne pyramidy

# Import the win32com.client module.
import win32com.client

# Create a variable to access the Geoprocessor.
gp = win32com.client.Dispatch("esriGeoprocessing.GpDispatch.1")

# nastaveni licence
gp.SetProduct("ArcInfo")

gp.Workspace = "D:\Vyuka\II-SKRI\Cviceni\DatabasePython\Tahoe\All"
rdList = gp.ListRasters ("a*")
rd=rdList.Next()

rdCount =0
while rd:
    gp.BuildPyramids_management (rd)
    print rd
    rd = rdList.Next()
    rdCount = rdCount +1
print rdCount


# ---SEZNAMY-FC----------------------------------------------------------------
# Procviceni metod Enumeration - List/ Cviceni 1
# verze vyuky 2012 /  10

import arcpy as ap
import string, os


ap.env.Workspace = "C:\\ucitel\\Dobesova_Zdena\\II - SKRI\\Cviceni\\Database\\Redlands.mdb"
ap.env.Workspace = "D:\\vyuka\\II - SKRI\\Cviceni\\Database\\Redlands.mdb"

ap.OverwriteOutput=1

## zjisti seznam datasetu
dsList=ap.ListDatasets("*","All")
for ds in dsList:
  print ds

# zjisti seznam trid prvku z geodatabaze
arcpy.env.Workspace = "D:\\vyuka\\II - SKRI\\Cviceni\\Database\\SanDiego.mdb"
fcList=ap.ListFeatureClasses()
for fc in fcList:
    print fc

# zjisti seznam trid prvku - shp z adresare
ap.env.Workspace = "D:\\vyuka\\II - SKRI\\Cviceni\\Database\\World"
shpList=ap.ListFeatureClasses()
for shp in shpList:
    print shp

# seznam rastru a tvorba pyramid
ap.env.Workspace = "D:\\vyuka\\II - SKRI\\Cviceni\\Database\\Tahoe\\Emer"
rdList = ap.ListRasters ("e*")
for rd in rdList:
  ap.BuildPyramids_management (rd)
  print "Pyramidy vytvoreny pro" + rd


# ---buffer railway----------------------------------------------------------------
# Import arcpy module
import arcpy


# Local variables:
DATA200_RailrdL = "D:\\VYUKA\\II - SKRI\\Cviceni\\Cv3_2012\\Data\\DATA200_RailrdL.shp"
RailrdBuff_shp = "D:\\VYUKA\\II - SKRI\\Cviceni\\Cv3_2012\\Data\\RailrdBuff55.shp"

# Process: Buffer
arcpy.Buffer_analysis(DATA200_RailrdL, RailrdBuff_shp, "500 Meters", "FULL", "ROUND", "NONE", "")


# ---buffer railway parameter----------------------------------------------------------------
# Import arcpy module
import arcpy

# Script arguments
# 1. argument
Railroad_line_feature_class = arcpy.GetParameterAsText(0)


# 2. argument
Output_feture_class_-_Railroad_Buffer = arcpy.GetParameterAsText(1)


# Process: Buffer
arcpy.Buffer_analysis(Railroad_line_feature_class, Output_feture_class_-_Railroad_Buffer, "500 Meters", "FULL", "ROUND", "NONE", "")


# ---parametr podruhe----------------------------------------------------------------
# Import arcpy module
import arcpy

# Script arguments
# 1. argument
Railroad_line_feature_class = arcpy.GetParameterAsText(0)

if Railroad_line_feature_class == '#' or not Railroad_line_feature_class:
    Railroad_line_feature_class = "DATA200_RailrdL" # provide a default value if unspecified

# 2. argument
Output_feture_class_-_Railroad_Buffer = arcpy.GetParameterAsText(1)

if Output_feture_class_-_Railroad_Buffer == '#' or not Output_feture_class_-_Railroad_Buffer:
    Output_feture_class_-_Railroad_Buffer = "D:\\VYUKA\\II - SKRI\\Cviceni\\Cv3_2012\\Data\\RailrdBuff.shp" # provide a default value if unspecified



# Process: Buffer
arcpy.Buffer_analysis(Railroad_line_feature_class, Output_feture_class_-_Railroad_Buffer, "500 Meters", "FULL", "ROUND", "NONE", "")


# ---HEEEEEEEEEELP EXAMPLE OF INPUT ARGUMENTS----------------------------------------------------------------
# help
# example of input arguments

import arcpy
from arcpy import env
import os

# Set the input workspace, get the feature class name to copy
#  and the output location.
#
env.workspace = arcpy.GetParameterAsText(0)
inFeatureClass = arcpy.GetParameterAsText(1)
outLocation = arcpy.GetParameterAsText(2)
outFeatureClass = outLocation + os.sep + os.path.basename(inFeatureClass)

# Copy feature class to output location
#
arcpy.Copy_management(inFeatureClass, outFeatureClass)




# ------------------------------------------------------------------
# ------------------------------------------------------------------

# ---SYNTAX-ERROR----------------------------------------------------------------
import arcpy, string
# import modul string!is necessary !

# Describe the Hospitals feature class.
ap.env.workspace = "D:\\Vyuka\\II - SKRI\\Cviceni\\Database"

dscFC = ap.Describe ("Redlands.mdb\\Hospitals")

# Print the shape type of the feature class to the Interactive Window.
# Use the string.lower function to avoid having to figure out if
# "point","polyline", and "polygon" are case sensitive.

if string.lower(dscFC.ShapeType) = "point":
    print "point"
elif string.lower(dscFC.ShapeType) == "polyline"
    Print "line"
elif string.lower(dscFC.ShapeType) == "polygon":
    print "polygon"
else:
    print "Do not know the type"


# ---MESSAGES----------------------------------------------------------------
# Cviceni 11, 3.skript
# datum: duben 2012
import  arcpy

# prazdna radka
arcpy.AddMessage(" ")
arcpy.AddMessage("Toto je zpr?va pro u?ivatele, pise se cerne.")

# prazdna radka
arcpy.AddMessage(" ")
arcpy.AddError ("Toto je chyba hl??en? u?ivateli, pise se cervene.")
arcpy.AddWarning("Toto je varov?n? pro u?ivatele, pise se zelene.")

# prazdna radka
arcpy.AddMessage(" ")


# ---CHYBA WORKSPACE TYPE----------------------------------------------------------------
# Cviceni 11
# datum: duben 2012
import  arcpy as ap
import sys

# upgrade geodatabaze (definice domeny atd. jen to lze delat s geodatabazi)
# nazev geodatabaze vstupuje jako argument
ap.env.workspace = sys.argv[0]
print ap.env.workspace
# nutna overit, zda je to opravdu geodatabaze a ne adresar, nebo dataset,...
dscWS = ap.Describe(ap.env.workspace)

dscWS = ap.Describe(" C:\ ")
print dscWS.workspaceType

#print dscWS.workspaceType

if dscWS.workspaceType == "FileSystem":
    print "Geodatabase neni platna!"
    ap.AddError ("Geodatabase neni platna, domena nebyla vytvorena, lituji.")
else:
    print "Geodatabaze overena, existuje"
    ap.AddMessage(" ")
    ap.AddMessage("Geodatabaze overena, existuje, vse OK.")
    ap.AddMessage(" ")
    ap.UpgradeGDB_management(gp.Workspace, "PREREQUISITE_CHECK", "UPGRADE")
    #ap.CreateDomain(gp.Workspace,"Roads", "Road types","TEXT","CODED")
    #ap.AddMessage("Dom0na vztvo5ena:")
    #ap.AddCodedValueToDomain(gp.Workspace, "Roads", "A", "Asfalt")
    #ap.AddCodedValueToDomain(gp.Workspace, "Roads", "P", "Paved")
    #ap.AssignDomainToField(gp.Workspace, "LocalRoads", "Roads")

del dscWS

# ---TRY-EXCEPT!!!!!!!!!----------------------------------------------------------------
import  arcpy as ap
try:
  # chybi workspace, kde je Railroads?, kam umistit vysledek Rail100 ?
  ap.Buffer_analysis("Railroads","Rail100",100)
except:
  # tisk ale jen do PythonWin
  print ap.GetMessages()
  # zkuste bez hlaseni i s hlasenim
  # bez hlaseni se jevi, jako ze vse probehlo spravne
  ap.AddMessage("Zde je hlaseni skriptu, pokud neco probehlo chybne. ")
  ap.AddMessage(" *********************************")
  ap.AddMessage(" ")
  ap.AddWarning(ap.GetMessages())
  ap.AddMessage(" ")

# --Ukazka tisku zprav a zjisten? poctu zprav----------------------------------------------------------------
# Ukazka tisku zprav a zjisten? poctu zprav

import  arcpy as ap

try:
  # nevykona se, neni nastaven workspace
  ap.Buffer_analysis("Railroads","Rail100",100)
except:
  # kod 2 - chybova hlaseni
  # kod 0 / vsechna hlaseni
  print ap.GetMessages(0)
  #ap.AddMessages(ap.GetMessages(1))
  print "Pocet zprav: "
  messageCount = ap.GetMessageCount()
  print messageCount
  print
  print "prvni zprava, index 0  "
  print ap.GetMessage(0)
  print "posledni zprava  "
  print ap.GetMessage(messageCount - 1)


# ---CREATE-FOLDER----------------------------------------------------------------

# ---CREATE-FOLDER----------------------------------------------------------------


